### ISSUE TITLE
项目引入nb_log，项目下面未自动nb_log_config.py文件

### ISSUE THREAD

**Issue by huanjoyous** [ydf0509/nb_log#1]
![image](https://user-images.githubusercontent.com/28851617/91001836-76285f80-e5ff-11ea-8afe-d2956c0adb11.png)

**Comment by ydf0509** [comment]
这是故意不在nb_log项目本身里面生成。要么你的测试代码和下载的nb_log项目不在同一个python项目下，要么使用pip安装nb_log
