### ISSUE TITLE
nb_log_config.py默认生成位置有问题

### ISSUE THREAD

**Issue by CNDrwei** [ydf0509/nb_log#10]
set_nb_log_config.py中101行  copyfile(Path(__file__).parent / Path('nb_log_config_default.py'), Path(sys.path[2]) / Path('nb_log_config.py')), sys.path[1]在pycharm中显示的是 ![image.png](http://ww1.sinaimg.cn/large/006qX6GLgy1gtm3it2844j30p70aa480.jpg)

**Comment by ydf0509** [comment]
你是故意调试nb_log_config的生成位置吗？你启动调试模式，sys.path[1]就变成那个调试插件的位置了，你别用pycahrm调试模式启动代码就行了。生产上你不可能用pyachrm调试来运行代码的。这没问题，nb_log是自动找到sys.path[1]，就是当前项目的根目录。

**Comment by ydf0509** [comment]
我不知道你为什么还是不信任nb_log_config的生成位置，居然去调试他，你别用pycahrm调试模式启动代码啊，你加个print打印调试不香吗。
