### ISSUE TITLE
支持windows多线程吗

### ISSUE THREAD

**Issue by chl916185** [ydf0509/nb_log#13]
支持windows多线程吗

**Comment by ydf0509** [comment]
这个问题是伪问题。任何日志handler都可以支持多线程安全，因为Handler基类已近吧emit方法加了线程锁。
![image](https://user-images.githubusercontent.com/26890690/132273673-640da2b0-8c83-4866-a4af-12184427ead6.png)




只需要关注时候，多进程是否安全，而且是关注 多进程 + 文件日志 + 文件日志需要按大小或者时间切割，需要满足这三个条件才需要关注是否多进程安全。
例如只使用控制台屏幕流日志，则压根不存在多进程是否安全的问题。
例如使用了控制台+文件日志，但文件没有设置成需要切割，则压根不存在多进程是否安全的问题。
例如使用了多进程 + 文件日志 + 文件日志需要按大小或者时间切割，此时需要关注多进程是否安全。nb_log很好的解决了多进程下问价你日志切割问题，并且性能远远超越任意为了多进程安全的ConcurrentFileHandler,也包括超越永不进行文件切割的FileHandler。nb_log是windwos和linux的多进程文件切割都兼容。
