### ISSUE TITLE
前置的提示可以去掉么？log的配置文件能换个位置么？

### ISSUE THREAD

**Issue by wangzhatian** [ydf0509/nb_log#18]
![image](https://user-images.githubusercontent.com/40046246/144214599-0e0d8821-3a7a-4d12-ae46-a33c57e7a269.png)

**Comment by ydf0509** [comment]
![image](https://user-images.githubusercontent.com/26890690/144214986-4f9319e1-0795-488b-a392-4a1e898a438d.png)
可以去掉，如图设置，但是99%的人一边抱怨颜色不好的问题，一边又嫌开头提示他怎么调颜色，现在的python码农太浮躁了。

为什么要换位置？默认生成在项目根目录是最好的。

**Comment by ydf0509** [comment]
你是pycahrm运行把？你的项目根目录是env/TestFlask吗？PYTHONPATH的作用要掌握好。

**Comment by ydf0509** [comment]
env/TestFlask 是项目根目录还是 python环境的目录？如果是前者，那你就没理解PYTHONPATH

**Comment by wangzhatian** [comment]
我用的是虚拟环境，环境下可能会有多个项目，如图
我修改下PYTHPATH


| |
王伊
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年12月1日 ***@***.***> 写道：


可以去掉，如图设置，但是99%的人一边抱怨颜色不好的问题，一边又嫌开头提示他怎么调颜色，现在的python码农太浮躁了。

为什么要换位置？默认生成在项目根目录是最好的。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ydf0509** [comment]
nb_log支持10000个python项目都没问题，都是生成在python项目的根目录，非pycahrm运行需要用户自己设置PYTHONPATH，如果是pycahrm以项目打开项目根目录，无需用户手动设置OYTHONPATH

**Comment by ydf0509** [comment]
教人这么设置PYTHONPATH不是本项目的义务范围，熟练的码农都知道

**Comment by ydf0509** [comment]
看博客，测试demo，精通PYTHONPATH很重要
https://www.cnblogs.com/ydf0509/p/15573807.html

**Comment by wangzhatian** [comment]
这个，知道了，pycharm默认的PYTHPATH
另外一个问题，我想在flask项目里使用这个日志框架，这个项目能不能自己拦截请求和响应？或者说日志模板里怎么设置HTTP请求参数？
| |
王伊
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年12月1日 ***@***.***> 写道：

教人这么设置PYTHONPATH不是本项目的义务范围，熟练的码农都知道

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangzhatian** [comment]
多谢，的确是没太留意PYTHONPATH


| |
王伊
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年12月1日 ***@***.***> 写道：

看博客，测试demo，精通PYTHONPATH很重要
https://www.cnblogs.com/ydf0509/p/15573807.html

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ydf0509** [comment]
> 
> 这个，知道了，pycharm默认的PYTHPATH
> 另外一个问题，我想在flask项目里使用这个日志框架，这个项目能不能自己拦截请求和响应？或者说日志模板里怎么设置HTTP请求参数？
> 

可以让flask日志更好看的，nb_log.get_logger（"flask"）就行了，你得明白name的作用，这是日志命名空间。
