### ISSUE TITLE
日志输出问题

### ISSUE THREAD

**Issue by Sencc** [ydf0509/nb_log#19]
nb_log很好用，不过遇到一个问题想请问一下，我用uwsgi启动Flask后，日志文件要等结束关闭程序后才有输出，这个有办法解决吗

**Comment by ydf0509** [comment]
nb_log_config.py  可以改配置，3是在各种场景下最稳的，试试 

修改log_file_hanlder_type 为3

![image](https://user-images.githubusercontent.com/26890690/147727046-dec35b1e-bd62-4b66-a3b5-e938dafb06b4.png)

**Comment by Sencc** [comment]
@ydf0509 感谢，这个方法可以解决
