### ISSUE TITLE
多个文件如何同时共用一个日志

### ISSUE THREAD

**Issue by pylemonorg** [ydf0509/nb_log#2]
在使用中，导入包的logger也使用配置的nb_log呢？

**Comment by ydf0509** [comment]
看readme已经说得十分明显了，logger日志是多实例的，例如loggera 可以写入a.log文件，loggerb可以写入b.log文件，你想写入a.log就调用loggera.debug,你想写入b.log，就调用loggerb.debug，没规定一个py文件只能有一个Logger类型的变量，你可以有logger3 loggger4 logger5 ，根据需要记录在哪些地方来调用哪个变量的logger.debug。
