### ISSUE TITLE
使用pyinstaller打包程序后，无法运行，找不到默认配置文件nb_log_config_default.py

### ISSUE THREAD

**Issue by TotoroQwQ** [ydf0509/nb_log#21]
![image](https://user-images.githubusercontent.com/8982154/150489324-52ccc329-809f-4ddd-a7a7-5f1b8d05c4dc.png)
又来了，好像不兼容pyinstaller打包，辛苦大佬看一下。感觉还是nb_log包和被引用的项目耦合性强了，强制指定了项目地址

**Comment by ydf0509** [comment]
自己在项目中先生自动生成好这个文件就行了，也可以自己复制到项目根目录下

**Comment by TotoroQwQ** [comment]
> 自己在项目中先生自动生成好这个文件就行了，也可以自己复制到项目根目录下

试了下，将这个文件复制一份到项目根目录下面也不行，还是报这个文件找不到，这个路径也挺奇怪的，并不是工作路径。
重新试了一个单文件的最简单程序也不行。
![image](https://user-images.githubusercontent.com/8982154/150920565-032a1979-c1c1-47a7-92bb-131fa3a143c7.png)

**Comment by ydf0509** [comment]
需要设置个 PYTHONPATH，要么就很low的在项目起点python脚本添加 sys.path.insert(1,项目根目录)

**Comment by TotoroQwQ** [comment]
> 需要设置个 PYTHONPATH，要么就很low的在项目起点python脚本添加 sys.path.insert(1,项目根目录)

打包后设置pythonpath还有用吗，设置了下，也是报错，我试试后者
![image](https://user-images.githubusercontent.com/8982154/150921252-5922cac3-f30c-4f92-af73-fdab8521c704.png)

**Comment by TotoroQwQ** [comment]
了解了一下pyinstaller原理，我是打包成onefile模式，最终是一个exe文件，但是运行时会在系统的临时文件夹里面生成一个目录，每次运行不一样，就是上面的那个奇怪的路径了，，，有点眉目，我试着改一下
https://blog.csdn.net/Mantana/article/details/112343895

**Comment by ydf0509** [comment]
print(sys.path[1])，项目如果没从这个中间件找到nb_log_config.py 就会自动复制文件，关键你要知道你的sys.path[1]是什么现在。

**Comment by TotoroQwQ** [comment]
> print(sys.path[1])，项目如果没从这个中间件找到nb_log_config.py 就会自动复制文件，关键你要知道你的sys.path[1]是什么现在。

现在不是pythonpath的问题，我在代码里面加了这个也没用。
```python
sys.path.insert(1, 'c:\\Users\\chens\\Desktop\\test')。
```
影响不到打包编译后的代码，设不设置都打印的下面这个。👇
```cmd
16:26:02  "nb_log\set_nb_log_config.py:40"   当前项目的根目录是：
 C:\Users\chens\AppData\Local\Temp\_MEI111602\lib-dynload    # 这是程序打印的初始
```
先不看这个，问题在于
- 1. 打包编译后的文件不是py文件，是pyc文件，复制py文件肯定报错
- 2. 基于1我想改成编译后复制pyc文件，发现文件存在但是拷贝仍然报错，说文件不存在，应该是临时文件不允许外部读写。
- 3. 基于2，我配置了权限，admin运行，也不行。
- 👇
```bash
# 这个是我在nb_log_default_config.py 里面加的一个打印Path(__file__)
path.file.default.py= C:\Users\chens\AppData\Local\Temp\_MEI111602\nb_log\nb_log_config_default.pyc

# 这是拷贝的报错信息
FileNotFoundError: [Errno 2] No such file or directory: 
'C:\\Users\\chens\\AppData\\Local\\Temp\\_MEI111602\\nb_log\\nb_log_config_default.pyc'
```
