### ISSUE TITLE
自动导入的包太多了 ，和原本应该使用的版本有冲突

### ISSUE THREAD

**Issue by ldw97** [ydf0509/nb_log#22]

**Comment by ldw97** [comment]
我项目用的pymongo是3.12.2但是这个需要安装3.5.1就没有办法安装··

**Comment by ydf0509** [comment]
> 我项目用的pymongo是3.12.2但是这个需要安装3.5.1就没有办法安装··

可以的，无视安装提示就行了，两个版本用法没有什么变化。
