### ISSUE TITLE
【建议】 默认安装只安装最基本依赖 & 可以设置是否在项目根目录生成nb_log_config.py

### ISSUE THREAD

**Issue by wordhui** [ydf0509/nb_log#23]
> 感谢大佬开源，不过使用过程中有些感想，总结为以下建议

#### 建议 默认安装只安装最基本的依赖，更多依赖（如mongo,ES等）采用   nb_log[xxx] 来安装
* 提高使用灵活度，减少依赖环境污染

#### 建议 可以关闭在项目根目录中生成 nb_log_config.py的功能
* 可以自由选择打开关闭此功能，提高使用灵活性

#### 建议 将带颜色日志的颜色定义可以通过一个字典覆盖default值 
```python
{
    "debug": "\033[38;5;214m", // 覆盖默认的颜色设置
    "error": "\033[35;5;214m",
    "info": "\033[38;5;196m",
}
```

**Comment by ydf0509** [comment]
颜色不是有代码决定的， 是由文字渲染终端决定的，控制台第一行就已经提示了需要用户在软件上设置，而不是再代码中设置print颜色。不同的主题和ide现实的颜色不一样，控制台第一行就提示了要设置了。

**Comment by ydf0509** [comment]
可以设置是否在项目根目录生成nb_log_config.py?  如果不生成，这么读取配置？如果用户每次需要指定从哪里读取配置文件岂不是更麻烦，建议看 pythonpathdemo 项目， 看pythonpath的作用。

在项目根目录生成配置文件咋了？多一个py文件没事吧？

**Comment by wordhui** [comment]
> 颜色不是有代码决定的， 是由文字渲染终端决定的，控制台第一行就已经提示了需要用户在软件上设置，而不是再代码中设置print颜色。不同的主题和ide现实的颜色不一样，控制台第一行就提示了要设置了。

确实不同主题下，颜色显示效果有区别，不过可能存在用户就想用主题A，自己想把主题A的日志颜色调节好看一点，而不是单向的调节主题，可以双向调节

**Comment by wordhui** [comment]
> 可以设置是否在项目根目录生成nb_log_config.py? 如果不生成，这么读取配置？如果用户每次需要指定从哪里读取配置文件岂不是更麻烦，建议看 pythonpathdemo 项目， 看pythonpath的作用。
> 
> 在项目根目录生成配置文件咋了？多一个py文件没事吧？

多个文件肯定没有问题的，但是不是每个人的所有项目都喜欢这种方式，不是每个人都讨厌稍微麻烦一点的方式，我觉得这个不是技术问题，是每个人的使用习惯问题，我的感觉是对于简单的项目不用读文件配置和nb_log_config.py，直接在单py文件顶部（或某个函数中）写死下配置就行，复杂的项目用户也可以自己指定配置文件的名称和路径，而不是固定项目根目录，所以我觉得作者可以考虑给用户一些选择的权利，以上都是个人拙见，感谢作者为开源做出的贡献！

**Comment by ydf0509** [comment]
单靠python内置的31 32 33 到37  41 到47调不出好看的颜色的，这些个颜色代码只能是大概的红橙黄绿青蓝紫，需要通过ide更精准的设置最好的颜色，通过代码永远无法精确控制显示效果的。必须通过ide中调节的，不行你试试就知道，把背景色打开，调出红尘黄绿青蓝紫，如果不调节ide中的颜色，无论你怎么改print的颜色代码，都不可能达到6中效果好，绝对是瞎眼。

**Comment by ydf0509** [comment]
> > 可以设置是否在项目根目录生成nb_log_config.py? 如果不生成，这么读取配置？如果用户每次需要指定从哪里读取配置文件岂不是更麻烦，建议看 pythonpathdemo 项目， 看pythonpath的作用。
> > 在项目根目录生成配置文件咋了？多一个py文件没事吧？
> 
> 多个文件肯定没有问题的，但是不是每个人的所有项目都喜欢这种方式，不是每个人都讨厌稍微麻烦一点的方式，我觉得这个不是技术问题，是每个人的使用习惯问题，我的感觉是对于简单的项目不用读文件配置和nb_log_config.py，直接在单py文件顶部（或某个函数中）写死下配置就行，复杂的项目用户也可以自己指定配置文件的名称和路径，而不是固定项目根目录，所以我觉得作者可以考虑给用户一些选择的权利，以上都是个人拙见，感谢作者为开源做出的贡献！

主要是万不自动生成，用户连nblog日志能配置什么项都不知道。

**Comment by ydf0509** [comment]
python的print /033 颜色代码只有31-37(前景) 41-47（背景） 91-97（前景）  101-107（背景），蓝色也有无数种的，有的蓝色背景无论文字是黑白都很难看，必须调ide的设置。如果是css有几千万种颜色，那么可以把颜色代码配置开放给用户，但是python不支持css #12FAA2 这样定义颜色，所以需要设置软件上的颜色。


如果nb_log不默认都根目录的固定文件，那用户每个脚本的起点种都要规定从哪里读取日志配置文件，这样真的太烦了。还是自动的读取好。
