### ISSUE TITLE
多进程日志的时间切分

### ISSUE THREAD

**Issue by Lucky-Jay** [ydf0509/nb_log#24]
大佬我想知道您的代码如何使用按照时间切分的多进程日志记录,我看着您这边只有封装好的按天分割的功能;我想使用那种自由设定时间的功能,方便我测试,您看您这边有啥可以直接用的吗?

**Comment by ydf0509** [comment]
你是说可以自己只有按时间，例如小时切割吗。

一般都是按天切割吧，台自由了，入参又要增加复杂化，现在参数太多了
