### ISSUE TITLE
remove_all_handlers 函数逻辑有问题

### ISSUE THREAD

**Issue by GSMix** [ydf0509/nb_log#25]
```python
def remove_all_handlers(self):
        for hd in self.logger.handlers:
            self.logger.removeHandler(hd)
```
这个函数有问题，对可迭代对象一边迭代一边删除，本身就有问题。

**Comment by ydf0509** [comment]
def remove_all_handlers(self):
        # for hd in self.logger.handlers:
        #     self.logger.removeHandler(hd)
        self.logger.handlers = []

谢谢。现在改了

**Comment by GSMix** [comment]
>   def remove_all_handlers(self):
>         # for hd in self.logger.handlers:
>         #     self.logger.removeHandler(hd)
>         self.logger.handlers = []
> 
> 谢谢。现在改了

后面有一个删除指定类型handler的函数也是这个问题

**Comment by ydf0509** [comment]
是的，看得很细心。修改了测试了。
用的比较少这2个移除handler的方法，谢谢指正。



![image](https://user-images.githubusercontent.com/26890690/159203056-2da9c332-527b-4440-943a-230006218471.png)

![image](https://user-images.githubusercontent.com/26890690/159203122-59b23681-96eb-4657-8f2a-4a4d3a27d30d.png)

![image](https://user-images.githubusercontent.com/26890690/159203013-d2dba10a-dfd8-4505-b4dc-1067a9966fad.png)


2222不会被打印了。
