### ISSUE TITLE
建议新增功能

### ISSUE THREAD

**Issue by FireJohnny** [ydf0509/nb_log#27]
1、压缩文件，达到多少后可以进行文件压缩
2、增加日志过滤功能，直接在log 初始化的时候增加全局的日志过滤，比如某些敏感字段，正则等等直接在日志的输出中就被mask掉了

**Comment by ydf0509** [comment]
第一个多少M压缩早就支持配置了，这么明显

第二个没做这个功能，用户自己的字符串自己区做过滤就行了。
