### ISSUE TITLE
打包成exe之后无法加载配置

### ISSUE THREAD

**Issue by restrain0324** [ydf0509/nb_log#28]
![image](https://user-images.githubusercontent.com/48167808/162113627-0e1ef0b7-4756-40f8-9681-fb426483fbe8.png)

**Comment by ydf0509** [comment]
还是要设置PYTHONPATH的，看pythonpathdemo项目。了解pythonpath的重要性

**Comment by restrain0324** [comment]
配置文件放过去之后就会报下面的错

**Comment by ydf0509** [comment]
打包肯定是支持的，检查打印下变量洛，你看我的pyqt5项目就是打包的包含了nb_log包
