### ISSUE TITLE
第一次的使用体验，我惊呆了，居然这样...

### ISSUE THREAD

**Issue by tasbox** [ydf0509/nb_log#29]
### 1.第一次使用时，我的狗眼差点闪瞎。

```python
from nb_log import LogManager,get_logger

# logger = LogManager('lalala').get_logger_and_add_handlers()
logger = get_logger('lalala') # 这个和上面的效果一样，但上面的LogManager还有其他公有方法可以使用。

logger.debug('绿色')
logger.info('蓝色')
logger.error('紫红色')
logger.critical('血红色')
print('print样式被自动发生变化')
```

当前调用了上面这段代码的时候（官网COPY的） 控制台打出了`五花八门`的输出(颜色)，还有一些包里面输出的内容。

### 2.一个日志包，集成了 `Mongodb`, `Elasticsearch` 等库

在我的工作做，我需要使用到 `Mongodb` 和 `Elasticsearch （7.6.1）`，在 `nb_log` 包中，`Elasticsearch` 的包时 `8.x`，因此到至了我之前使用 `Elasticsearch` 的代码无法正常工作了。

### 4.吐槽就到这里，以上观点仅代表个人（无喷点）单纯的描述使用体验。

**Comment by ydf0509** [comment]
1、那你有没有反思你颜色瞎眼，我颜色好看？控制台第一行就提示你了颜色设置，你不看有啥办法。
2、使用nb_log为什么影响你用elastic 8.x版本，你升级安装成8.x不就好了吗，这个太容易解决了，requestment.txt先写nb_log，再写elasticserch版本覆盖就好了，你以为nb_log必须使用那个7.6.1版本号吗？

**Comment by tasbox** [comment]
回复的还挺快的。
第一个颜色的问题，第一个输出的颜色对于用户来说不是友好的，会破坏第一次的感觉。颜色实在太瞎眼了。
第二个包的问题，你的牛逼日志包默认安装的就是8.x的版本，像我这样都吃过一次亏了，你不提醒还真不知道能。

**Comment by ydf0509** [comment]
你还是没懂python 033颜色和终端软件渲染的最终颜色之间的关系，我只能这么说。多看文档吧先，你以为和软件和主题没关系吗
这是很常见的问题，三方包依赖什么版本，不是就一定永不了其他版本，只是偷懒写死了，坐着懒得测试所有版本的兼容性而已。太常见了，你使用三方包的经验不足，以为三方包说依赖什么版本，你不按照三方包的依赖，电脑就会爆炸一样，你自己开发一个包就知道了

**Comment by tasbox** [comment]
## 关于第三方包依赖的问题

你可以去试试玩玩机器学，深度学习，训练的包。如果不按照指定依赖包来安装，那么都是错误一大堆了。

## 结尾

其他的就不讨论了，接下来作者加油吧。现在也有 113 的 Start 了。

**Comment by ydf0509** [comment]
> ## 关于第三方包依赖的问题
> 你可以去试试玩玩机器学，深度学习，训练的包。如果不按照指定依赖包来安装，那么都是错误一大堆了。
> 
> ## 结尾
> 其他的就不讨论了，接下来作者加油吧。现在也有 113 的 Start 了。

大胆点，把elastic升级成你想要的版本，电脑炸了我配你。你日志只要不使用写入ellastic的功能，你安装和nblog不匹配的es版本怎么就会报错了

**Comment by tasbox** [comment]
`elasticsearch` 每个版本之前的变动。日志功能的确没有使用 ES，但是我项目是跟ES有关系的，8.ｘ的版本无法跑起来而已。但也不至于炸电脑☠️

**Comment by ydf0509** [comment]
![image](https://user-images.githubusercontent.com/26890690/175440498-e8a42cce-9551-4294-9c94-02dd673f1971.png)

说颜色不好看的，自己又不看控制台提示，你太浮躁了没办法。
你看看我的颜色
