### ISSUE TITLE
在gunicorn中使用会报错MonkeyPatchWarning

### ISSUE THREAD

**Issue by kingdomad** [ydf0509/nb_log#30]
/usr/local/python3/lib/python3.7/site-packages/gunicorn/workers/ggevent.py:38: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016.

请问大佬要如何解决

**Comment by ydf0509** [comment]
这只是警告，这和nb_log毫无关系，你自己import requests也会报这个警告。
你自己要用gevent启动web服务，就最好在app的第一行加上from gevent import monkey；monkey.patch_all()，这是常识啊，你既然要用gevent并发模式启动web并发，就该知道啥是gevent。妖魔你就指定使用线程方式启动。
