### ISSUE TITLE
我有点强迫症，这里文件路径和行数，最后一个数字和前面颜色不一样，怎么破解啊，

### ISSUE THREAD

**Issue by nicknamexiaozui** [ydf0509/nb_log#34]
![8](https://user-images.githubusercontent.com/79073164/183844482-88bfcd96-ec2a-4ea7-a352-70de7dc49ba7.png)

**Comment by ydf0509** [comment]
这个我已经知道了，最后一个字母颜色不一样，这无法解决，这是pycahrm自动的。

**Comment by nicknamexiaozui** [comment]
好的。
