### ISSUE TITLE
在哪个函数的哪个参数设置格式化字符串？

### ISSUE THREAD

**Issue by zhangjing-GitHub-Code** [ydf0509/nb_log#36]
是在logger=LogManager("LOGMAIN",...(这里)).get_logger("MAIN")
还是logger=LogManager("LOGMAIN").get_logger("MAIN",...(这里))?
或者是哪里?..?
python logger是用的basicConfig，但nb_log没有（？）

**Comment by ydf0509** [comment]
nb_log的get_logger就是原生logger对象，当然支持basicConfig。

但没有必要，basicConfig字典过于复杂，容易写错。nb_log的get_logger通过入参自动设置了formmer个handler还有级别。

**Comment by ydf0509** [comment]
你怎么那么浮躁看，get_logger 方法入参介绍清清楚楚明明白白，  formatter_template

**Comment by ydf0509** [comment]
你太浮躁了吧，这么清楚，底下还有中文注释
```python
def get_logger(name: typing.Union[str, None], *, log_level_int: int = None, is_add_stream_handler=True,
               do_not_use_color_handler=None, log_path=None,
               log_filename=None, log_file_size: int = None,
               log_file_handler_type: int = None,
               mongo_url=None, is_add_elastic_handler=False, is_add_kafka_handler=False,
               ding_talk_token=None, ding_talk_time_interval=60,
               mail_handler_config: MailHandlerConfig = MailHandlerConfig(), is_add_mail_handler=False,
               formatter_template: int = None) -> logging.Logger:

```

**Comment by zhangjing-GitHub-Code** [comment]
`AttributeError: 'LogManager' object has no attribute 'get_logger'`, ~LogManager不能getlogger？（还是方法不对）~(((，我看README用的是get_logger_and_add_handler，
and，我想要自定义格式字符串，改config文件？

**Comment by ydf0509** [comment]
logger_aa = LogManager('aa').get_logger_and_add_handlers(10, log_filename='aa.log')
logger_bb = get_logger("bb", log_level_int=30, is_add_stream_handler=False, ding_talk_token='your_dingding_token')
logger_cc = get_logger('cc', log_level_int=10, log_filename='cc.log')

你不需要用 LogManager类，这里面有一些高阶用法，不懂logging包的人理解不了。一般人直接get_logger函数就好了

**Comment by ydf0509** [comment]
你是用什么ide写代码，我有点好奇。不存在的方法不能补全还有波浪线红色提示，去装个pycahrm自动补全提示把。

**Comment by zhangjing-GitHub-Code** [comment]
Python IDLE😅，就小写个记录剪切板。
