### ISSUE TITLE
默认设置覆盖不完全

### ISSUE THREAD

**Issue by WitchSeele** [ydf0509/nb_log#39]
启动的前两句必须修改nb_log_config_default才能改到，修改set_nb_log_config文件没用

**Comment by ydf0509** [comment]
你说的都是错的，nb_log_config_default和set_nb_log_config都是nb_log的源码，我怎么可能这么low，用户要修改源码。

用户只用关心修改 nb_log_config.py 就好了，不会要求用户修改nb_log的源码。

**Comment by WitchSeele** [comment]
那打包问题呢，中间文件路径用的环境路径导致打出来的包找文件找不到
