### ISSUE TITLE
nb_log_config.py 已经生成，依然打印大块的提示信息

### ISSUE THREAD

**Issue by hugo2017** [ydf0509/nb_log#4]
![info](https://user-images.githubusercontent.com/26821452/117604755-c729b500-b188-11eb-9373-3c8ed479a14d.jpg)

可能有点代码洁癖，已经生成了配置文件，建议不要再显示此提示信息。

**Comment by ydf0509** [comment]
配置文件中已近考虑到这个了，主要是必须提示用户怎么设置ide优化颜色，不然又得用户抱怨颜色不好看。你不想提示你怎么配置颜色，可以在 nb_log_config.py 设置 WARNING_PYCHARM_COLOR_SETINGS = Flase
