### ISSUE TITLE
pycharm调试首次创建配置文件目录异常

### ISSUE THREAD

**Issue by setloser** [ydf0509/nb_log#40]
引入nb_log直接进行调试运行，set_nb_log_config文件中的Path(sys.path[1])会读取到pycharm的调试文件目录，也就是pycharm安装目录下的plugins\python\helpers\pydev目录，生成的nb_log_config文件会在该目录下，而不是程序根目录，使用运行这不会出现此问题，目前我测试到将ath(sys.path[1])改为ath(sys.path[0])即可正常获取，以上仅供参考，如有问题望请大神指正，感谢！

**Comment by ydf0509** [comment]
nb_log要以run方式启动，才能正确使用sys.path1,你第一次运行项目时候，使用run模式随便启动一下就好了，就会自动生成到项目根目录了。以后每次用调试模式就能自动import到配置文件了。首次运行项目不要以调试模式运行。

这不是什么大问题。主要是你要用正常run模式运行一下就好了。
