### ISSUE TITLE
Log level for handler is hardcoded?

### ISSUE THREAD

**Issue by killbus** [ydf0509/nb_log#42]
https://github.com/ydf0509/nb_log/blob/c0f5d2979c8e50a43f15399a0683ecf1650b17f6/nb_log/log_manager.py#L331

**Comment by ydf0509** [comment]
formattor对象可以设置日志级别，logger对象也可以设置日志级别的。这是自由组合的，例如你logger是info级别，handler设置debug级别，最终你使用logger.debug还是不会记录日志的。handler级别如果是warnig，你logger.info也不会记录的。
nb_log是把添加hanlder内置化了，不希望暴露太多自由复杂组合的hanlder，所以这里设置10没毛病的。如果handler级别比logger级别低，那就是按照logger的日志级别了，例如你设置logger日志级别为logging.ERROR,你的handler级别设置DEBUG INFO ERROR 都是等效的，只要handler级别不高于logger的级别，你设置任何handler级别都是一样的效果。


你现在出了啥问题呢，难道你设置logger日志界别为20，我代码的handler级别设置了10，难道导致记录了你logger.debug的消息了吗。

**Comment by ydf0509** [comment]
你意思是先一个logger，根据不同的消息级别，高级别的严重消息发钉钉。


nb_log希望用户实例化两个不同的logger来实现这件事情，例如logger2 = nblog.get_logger("aaa",is_add_dingtalk=True),这样你用logger2.info的就会记录到钉钉了，你不希望发钉钉的消息用logger1 =  nblog.get_logger("bbb",) logger.info（） 就可以了。
使用不同的logger对象就好了，这样就可以控制某条消息发送钉钉了

**Comment by ydf0509** [comment]
> 如果命名空间像这种 `get_logger('django.request')` 的，如何实现呢？

logging包内置的，用了享元模式。
logging.getLogger("abcd") is logging.getLogger("abcd") 结果是True，
logging.getLogger("abcd") is logging.getLogger("efgh") 结果是False，

**Comment by ydf0509** [comment]
可以的，你这样写
