### ISSUE TITLE
logger.success

### ISSUE THREAD

**Issue by xjian32** [ydf0509/nb_log#45]
希望可以添加success类型的日志

**Comment by xjian32** [comment]
> nb_log要做到与内置logging百分之百兼容，你是想logger.sucess(“hello”) 这样吗

嗯，是的。因为我现在的项目中是用的loguru，有很多地方用到了success类型的日志，所以做不到无缝切换。

**Comment by ydf0509** [comment]
要养成好习惯，使用经典logging兼容的方式。

如果你非要兼容logger.sucecess,可以在代码开头写
import logging
logging.Logger.sucess=logging.Logger.info

之后你就可以使用logger.sucess自动调用logger.info了
