### ISSUE TITLE
启动时的项目路径和配置提示log没有单独配置项

### ISSUE THREAD

**Issue by RookieApe** [ydf0509/nb_log#46]
启动时的项目路径和配置提示log没有单独配置项，只能修改源码

**Comment by ydf0509** [comment]
不需要修改源码，你没懂PYTHONPATH。看我写的pythonpathdemo项目。

**Comment by RookieApe** [comment]
新手自学的python，我看了你写的 pythonpathdemo项目，例子能看明白，但是还是没懂 怎么配置PYTHONPATH，可以做到不打印项目路径的log，希望有空的时候能具体解惑下，谢谢
