### ISSUE TITLE
nb_log识别出的nb_log_config.py所在路径，是个错误路径

### ISSUE THREAD

**Issue by whitePythonLearn** [ydf0509/nb_log#47]
failed: Importing listener 'D:\robotframework_smartHub3.0\rf_smarthub3.0\python_files\RobotListener.py' failed: FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Python39\\Scripts\\robot.exe\\nb_log_config.py'
执行文件RobotListener.py调用mylog.py
![image](https://user-images.githubusercontent.com/40603318/198872084-7ebde188-6094-4f49-b005-96c90eae9e51.png)
mylog.py:
![image](https://user-images.githubusercontent.com/40603318/198872118-d96555ce-ec8b-48bf-b304-07f353e01f22.png)
项目结构:
![image](https://user-images.githubusercontent.com/40603318/198872184-06e41c3e-9fe0-41d8-a2fd-2c35bd0c752b.png)

**Comment by whitePythonLearn** [comment]
补充一下，单个执行RobotListener.py，日志生成是正常的。
我的是robotframework项目，发生错误的操作是执行了robotframework的执行命令：
D:\Python39\Scripts\robot.exe --listener D:\robotframework_smartHub3.0\rf_smarthub3.0\python_files\RobotListener.py -d D:\robotframework_smartHub3.0\rf_smarthub3.0 D:\robotframework_smartHub3.0\rf_smarthub3.0\smartHub\测试数据构造\测试数据构造.robot

**Comment by ydf0509** [comment]
D:\Python39\Scripts\robot.exe\nb_log_config.py   这种就是sys.path[1]识别错误，因为你打包成exe了，sys.path[1]发生了变化。

你自己使用PYTHONPATH或者sys.path.insert来使nb_log_config.py在sys.path的文件夹列表中的任何一个文件夹下面的位置就行了。
