### ISSUE TITLE
pyinstaller 打包启动失败

### ISSUE THREAD

**Issue by geekzsp** [ydf0509/nb_log#52]
如果设置console=True可以正常启动，设置为False 则无法启动

**Comment by ydf0509** [comment]
看文档9.4   https://nb-log-doc.readthedocs.io/zh_CN/latest/articles/c9.html

**Comment by geekzsp** [comment]
> 看文档9.4 https://nb-log-doc.readthedocs.io/zh_CN/latest/articles/c9.html

pyinstaller在设置console=False 时候 sys.stdout会为null 导致这个地方报错了
<img width="344" alt="image" src="https://user-images.githubusercontent.com/23443948/215938948-f0f7ad55-6490-4f5b-a2b4-b1b985ab19ac.png">

**Comment by ydf0509** [comment]
nb_log_config.py 可以设置 patch_print 为False的

**Comment by geekzsp** [comment]
> patch_print

set_nb_log_config.py 是在这个开关之前就执行的，里面的标准输出没有这个判断。

**Comment by ontisme** [comment]
已照著 9.4 文檔操作，也在全新專案嘗試打包過，都會出現以下問題
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "nb_log_config.py", line 22, in <module>
ModuleNotFoundError: No module named 'pythonjsonlogger'
```

* 確定有安裝 `pythonjsonlogger` 
* 也在 `spec` 嘗試過 
```
pathex=['.\\venv\\Lib\\lsite-package'],
```
* 嘗試過在 main.py 入口 import 這個庫

實在不清楚為什麼這個包不進去

**Comment by ontisme** [comment]
> 已照著 9.4 文檔操作，也在全新專案嘗試打包過，都會出現以下問題
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 1, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
>   File "nb_log_config.py", line 22, in <module>
> ModuleNotFoundError: No module named 'pythonjsonlogger'
> ```
> 
> * 確定有安裝 `pythonjsonlogger`
> * 也在 `spec` 嘗試過以下
> 
> ```
> pathex=['.\\venv\\Lib\\lsite-package'],
> ```
> 
> * 嘗試過在 main.py 入口 import 這個庫
> 
> 實在不清楚為什麼這個包不進去
