### ISSUE TITLE
ConcurrentDayRotatingFileHandler

### ISSUE THREAD

**Issue by GoldCity5** [ydf0509/nb_log#55]

**Comment by ydf0509** [comment]
代码和操作系统类型（win / linux）发下才知道

**Comment by GoldCity5** [comment]
`
from flask import Flask
import nb_log


log_path = "/logs"
log_filename = "test.log"
logger = nb_log.LogManager("root").get_logger_and_add_handlers(1, log_path=log_path, log_filename=log_filename, log_file_handler_type=2)

app = Flask(__name__)



@app.route('/hello-world')
def hello_world():
    logger.info("hello world")
    return 'Hello, World!'


logger.info("start")
logger.info(logger.handlers)



if __name__ == '__main__':
    app.run(host="0.0.0.0", port=3077, debug=False)`
    
    
    

macOS 系统

**Comment by ydf0509** [comment]
![image](https://user-images.githubusercontent.com/26890690/232955956-9ba6db07-534e-4122-a689-8cff9b5eea9b.png)
lograte 了解下。

**Comment by GoldCity5** [comment]
我需要按天切割日志，ConcurrentDayRotatingFileHandler这个看起来更符合需求呢

**Comment by ydf0509** [comment]
安装外部工具，lograte灵活，可以按天 按大小

**Comment by ydf0509** [comment]
你falsk直接运行的， 还是uwsgi部署

**Comment by GoldCity5** [comment]
本地是直接运行，生产环境是gunicorn+flask

**Comment by ydf0509** [comment]
from nb_log import get_logger

logger = get_logger('mylog',log_filename='mylog4c.log',log_file_handler_type=2)


for i in range(10):
    logger.error(f'testss {i}')

**Comment by GoldCity5** [comment]
好像不行，你这个是程序结束了才会写入，在程序运行期间 看不到日志


`import time

from nb_log import get_logger


log_path = "/Users/kongweilong/mindverse/project/log_configer/logs"
log_filename = "test.log"

logger = get_logger('mylog', log_path=log_path, log_filename=log_filename, log_file_handler_type=2)


for i in range(10):
    logger.error(f'testss {i}')




logger.error("ok")

time.sleep(100)`

**Comment by ydf0509** [comment]
![image](https://user-images.githubusercontent.com/26890690/232959867-cd89a414-658c-4c44-9f08-a752bab23d8f.png)
1043行的测试时候注释了，要放开。

**Comment by ydf0509** [comment]
1043行的flush放开。  为了性能，归根结底在生产环境最好用 lograte + watchedfilehandler。学习下lograte，不要用python的确保多进程安全的按天切割了。

**Comment by GoldCity5** [comment]
好的，感谢🙏，这里的flush是原本设计如此吗，还是说是bug，可以放开呢

**Comment by ydf0509** [comment]
先安装8.4，但最好用lograte，lograte的各种切割备份自定义真的很强大

**Comment by GoldCity5** [comment]
好的，我得学一下
