### ISSUE TITLE
导入就报错

### ISSUE THREAD

**Issue by CoderHaay** [ydf0509/nb_log#57]
from nb_log import get_logger
新环境安装完，只贴了demo代码就报错了：
No such file or directory: '\\pythonlogs\\2023-07-03.Logs_Learing.print'

**Comment by CoderHaay** [comment]
<img width="919" alt="微信截图_20230703190247" src="https://github.com/ydf0509/nb_log/assets/109799680/fbcb0802-479f-4e98-a898-0d80e095ca93">

**Comment by ydf0509** [comment]
稍等下，昨天更新了强力的猴子补丁，生成配置文件的模块要去掉导入monkey print，先安装8.8版本你。

**Comment by ydf0509** [comment]
现在自动创建文件夹了，安装9.4

**Comment by CoderHaay** [comment]
非常感谢已经可以正常使用了，正在啃文档。有个建议：导入库之后，控制台打印出来了很多说明信息，这些信息能否通过配置控制是否打印出来呢？毕竟熟手后面就不用看这些说明了。

**Comment by ydf0509** [comment]
可以关闭设置颜色提示，但不建议关闭颜色提示，90%的人压根没看提示，就关了，以后又抱怨颜色问题不好。非常痛恨这种人，提示了不看 还乱抱怨

**Comment by CoderHaay** [comment]
你好，生成的配置文件里面说明 `可以设置 WARNING_PYCHARM_COLOR_SETINGS = False`, 应该是：
SHOW_PYCHARM_COLOR_SETINGS = False
添加到生成的 nb_log_config.py 里面；
