### ISSUE TITLE
flask项目，crash

### ISSUE THREAD

**Issue by CoderHaay** [ydf0509/nb_log#58]
![image](https://github.com/ydf0509/nb_log/assets/109799680/223e0064-a619-43dd-b654-aaade03b70b7)
![image](https://github.com/ydf0509/nb_log/assets/109799680/d196061c-3d10-4b6c-a798-3cd6374aa869)

两个问题：
`1.  根目录不知道为啥读取到虚拟环境里面去了；`
`2. 闪退`

**Comment by ydf0509** [comment]
代码顶部 print sys.path[1] 看下。

**Comment by ydf0509** [comment]
正常当前启动py脚本所在的文件目录是sys.path[0]   ,项目根目录是 sys.path[1]

**Comment by ydf0509** [comment]
歧这些问题，归根结底是要懂pythonpath，归根结底是要知道pytjonpath和模块导入机制，一个模块被import导入，是从哪里开始搜寻查找的。这是很重要的基础常识 。这个知识点和nblog毫无关系，即使你不用nblog也需要掌握这个知识，太重要了。

**Comment by ydf0509** [comment]
print sys.path啊，print sys.path[1]，哎 。你print一下吧

**Comment by ydf0509** [comment]
第一个问题你打印下 sys.path，代码第一行打印
