### ISSUE TITLE
linux下使用LOG_FILE_HANDLER_TYPE = 2时报错I/O operation on closed file.

### ISSUE THREAD

**Issue by Paihuai-D** [ydf0509/nb_log#59]
当我修改LOG_FILE_HANDLER_TYPE = 1为LOG_FILE_HANDLER_TYPE = 2时，会报错：
I/O operation on closed file.
--- Logging error ---
Traceback (most recent call last):
  File "/home/chenzhen/.local/lib/python3.8/site-packages/nb_log/handlers.py", line 1042, in emit
    self.fp.write(msg + '\n')
ValueError: I/O operation on closed file.
但是当LOG_FILE_HANDLER_TYPE = 1的时候，不会出现该错误，我该如何修改才能实现LOG_FILE_HANDLER_TYPE = 2。谢谢您！！！

**Comment by Paihuai-D** [comment]
> 发下你的完整代码

此处是我定义logger:
logger_state = \
    get_logger(name='MsgState',
               log_level_int=10,
               log_path=METAINFO.logLocation,
               log_file_size=100,
               log_file_handler_type=2,
               log_filename='msg_state.log')
此处是代码调用地方：
    def run(self):
        while not rospy.is_shutdown():
            self.publish_events()
            self.publish_report_data()
            current_time = rospy.Time.now()
            if current_time >= self.send_time1:
                self.publish_states()
                self.send_time1 = rospy.Time.now() + rospy.Duration(120.0)  
                logger_state.info("The current status is normal")
此处是调用run函数：
if __name__ == '__main__':
    event_handler = MessageHandler()
    event_handler.run()

**Comment by ydf0509** [comment]
看不到你的全部代码。 用第6种handler试试。  同时按大小和时间切割。

**Comment by Paihuai-D** [comment]
> 看不到你的全部代码。 用第6种handler试试。 同时按大小和时间切割。

第6种可以运行
