### ISSUE TITLE
安装时附带安装的库过多，其中部分的对已有项目的会有影响

### ISSUE THREAD

**Issue by jsonvot** [ydf0509/nb_log#60]
首先，这个日志库的使用很人性化，极大的简化的使用操作，感谢大佬的辛苦奉献！
但是在安装的时候发现了如下的一些问题：
如图，当执行pip安装后，默认安装了很多最新版本的库，当某些老项目使用咱们的日志库的时候，可能版本会有冲突，其次，对于只是简单的记录一下日志的同学，可能很多库压根就用不到。
![33](https://github.com/ydf0509/nb_log/assets/23091750/94417f85-7508-4f96-b716-362204168e21)
基于上面的情况，希望作者能支持在安装时对需要库进行可选安装。类似tortoise-orm的库那样就太好了。比如执行pip install nb_log就是安装核心基础功能的，pip install nb_log[kafka,mongo,flask] 就是核心+包含了kafka,mongo,flask等扩展的
![1111](https://github.com/ydf0509/nb_log/assets/23091750/c7a20ea7-46fa-4322-95aa-5c0f471e6b59)

**Comment by jsonvot** [comment]
@ydf0509

**Comment by ydf0509** [comment]
我知道你说的这种选装,鲁抗funboost的setup.py 就知道了,选装打包不难.

但是我好奇为什么影响了你现有项目呢,版本不一样是无所的,我固定了第三方包的版本为唯一版本是懒得大规模兼容测试,并不是还说nb_log要求 kafka-python==2.0.2 就一定要安装这个版本,实际上一般情况下只要三方包没有翻天覆地大概特改,任何kafka-python版本都可以,自己测试就知道了.  


例如你想安装 kafka-python == 2.3.1

你requiorements.txt 先写 nb_log==10.2,再写   kafka-python == 2.3.1 就好了,并不会造成项目报错启动不了,你不太懂python的依赖,以为某个包写了依赖三方包的 2.0.2版本,安装其他版本一定报错,不是这样的.


为什么我没写 1.6.9 < kafka-python  <3.5.6 这样写个区间呢,因为我没有时间大规模测试每个依赖三方包的版本,你自己想安装什么版本的 kafaka-pythoin都是你自己想安装什么版本就行,只要能启动没报错就说明是兼容的.

**Comment by ydf0509** [comment]
https://pypi.org/project/fast-log-nb/

你可以使用fast_log项目.没有任何依赖,简单快速.
