### ISSUE TITLE
反馈一个参照了9.4后仍出现的打包bug与解决办法

### ISSUE THREAD

**Issue by HSLix** [ydf0509/nb_log#61]
首先感谢大佬制作的nb_log,省了很多事，同时也促进我去学习pythonpath等知识
然后，我在用installer打包我的程序时，有按照9.4添加nb_log_config，但运行后程序有如下报错

……AttributeError: 'NoneType' object has no attribute 'write'

喂给gpt后，提示我问题出在File "nb_log\simple_print.py", line 19, in stderr_write

于是我上网找答案，在simple_print.py 19行加入以下代码解决问题，希望对其它人有用

#添加stderr通道
for _name in ('stdin', 'stdout', 'stderr'):
	if getattr(sys, _name) is None:
		setattr(sys, _name, open(os.devnull, 'r' if _name == 'stdin' else 'w'))

然后也想请作者解答一下原因，比如应对这个问题还有什么更好的办法来解决
总之多谢作者的辛苦工作和无私奉献

**Comment by ydf0509** [comment]
的确是,用win32serviceutil服务方式后台运行也是报错AttributeError: 'NoneType' object has no attribute 'write',

打包后运行, sys.stderr是None,None没有.write方法,  你升级下nb_log 11.6版本,我改了.

**Comment by WH2425** [comment]
<img width="727" height="401" alt="Image" src="https://github.com/user-attachments/assets/73846802-264b-4d4d-af48-d950ec03efc3" />
使用Version: 13.2，还是会有这个报错啊

**Comment by ydf0509** [comment]
> 包括最新版本，打包还是会有这个报错 [@ydf0509](https://github.com/ydf0509)

当时解决了, 但后来又加了一个骚气的 print自动同时写入文件的功能模块, 所以又出错了,还得再兼容下.
