### ISSUE TITLE
是否默认使用 loguru的控制台日志只能设置为False? [用户loguru版本太古老]

### ISSUE THREAD

**Issue by miyaosk** [ydf0509/nb_log#64]
当设置 `DEFAULUT_IS_USE_LOGURU_STREAM_HANDLER = True` 时，logger打印日志报错

`TypeError: __init__() got an unexpected keyword argument 'patchers'`

**Comment by ydf0509** [comment]
我刚才试了,可以设置为 DEFAULUT_IS_USE_LOGURU_STREAM_HANDLER = True
设置为True时候,默认使用loguru的颜色方式.

![image](https://github.com/ydf0509/nb_log/assets/26890690/7e9ad539-4629-4956-b9e9-1fc8afef7143)



或者你说一下nb_log版本,然后吧错误截个长图,我才知道为什么报错

**Comment by ydf0509** [comment]
我估计是你loguru版本不同,不接受pathcers入参,

![image](https://github.com/ydf0509/nb_log/assets/26890690/965a2295-18b2-4d8c-9be5-07fcc605496f)

那我去掉这个入参把.

**Comment by ydf0509** [comment]
你要检查一下你的loguru版本

![image](https://github.com/ydf0509/nb_log/assets/26890690/cdedbc90-a7da-4d61-b099-62eb11127c43)

**Comment by ydf0509** [comment]
你使用最新的 loguru 0.7.2试试吧,估计你是四五年没升级loguru版本了.

**Comment by miyaosk** [comment]
> 你使用最新的loguru 0.7.2试试吧，估计你是四五年没升级loguru版本了。

是的，升级后可以使用了

**Comment by ydf0509** [comment]
我喜欢nb_log色彩模式,使用户不肯花10秒钟按照控制台提示设置pycharm,导致颜色没有文档图片的好.
