### ISSUE TITLE
I/O operation on closed file错误

### ISSUE THREAD

**Issue by sunny6chen** [ydf0509/nb_log#65]
1. log_file_handler_type == 2时 会出现I/O operation on closed file的错误。

系统信息：MACOS
版本：nb-log= "~=12.3"

日志：
--- Logging error ---
Traceback (most recent call last):
  File "/nb_log/handlers.py", line 684, in emit
    self.fp.write(msg + '\n')
ValueError: I/O operation on closed file.

**Comment by ydf0509** [comment]
日志写入进去没?

**Comment by ydf0509** [comment]
这个应该没影响吧,你按了ctrl c 或者代码异常结束,不影响写入日志

**Comment by sunny6chen** [comment]
没有写入到日志文件内， 这是在fastapi的RequestRoute方法内，记录请求日志时，出现的错误

**Comment by ydf0509** [comment]
你用hanlder 6试试呢

**Comment by sunny6chen** [comment]
其它type没问题，就2会出现上方错误
