### ISSUE TITLE
is_add_elastic_handler =True 后 报错 Action/metadata line [1] contains an unknown parameter [_type]

### ISSUE THREAD

**Issue by anjia0532** [ydf0509/nb_log#68]
配置了 `is_add_elastic_handler=True` 后 报`Action/metadata line [1] contains an unknown parameter [_type]`

把 https://github.com/ydf0509/nb_log/blob/master/nb_log/handlers_more.py#L391 删除 `_type` 后正常

我的环境是
```
python 3.11

funboost 43.3
  -> 自动安装的 nb_log和elasticsearch
  nb_log12.4
  elasticsearch 8.13.0
```

elasticsearch server 是 elasticsearch:8.11.1

**Comment by ydf0509** [comment]
把  _type的值固定写 '_doc' 试试

**Comment by ydf0509** [comment]
不同的es服务版本不同,es 服务端高版本不用设置 doc_type

**Comment by ydf0509** [comment]
那我测试时候没用那么高的服务端版本,高版本去掉了 doc_type

**Comment by ydf0509** [comment]
![image](https://github.com/ydf0509/nb_log/assets/26890690/9326ad11-7dc2-47f9-b05f-6ccde7ec1d03)
![image](https://github.com/ydf0509/nb_log/assets/26890690/366a01c6-9dae-4a34-88c6-6d54e59c4b40)

这是elatic的改版历史

**Comment by ydf0509** [comment]
es高版本服务端不能传type了.

**Comment by ydf0509** [comment]
提交代码了,今后不兼容es7以前的服务端.

**Comment by anjia0532** [comment]
对，es 有好多破坏性更新，相对来说往logstash写数据兼容性更好些（当然性能肯定赶不上直写ES）

**Comment by ydf0509** [comment]
目前好像很少人使用 控制台和文件以外的日志handler,99%的人认为日志就是控制台和写文件,我自己也比较少用es mongo 这些handler.

**Comment by anjia0532** [comment]
我对 python 生态了解的不太多，我这边主要用的Java。微服务场景下Java这边用ELK(ES,Logstash,Kibana)还挺常见的（否则的话一个业务跨多个应用或者多个模块，日志分布在不同的模块，服务器，机房，容器，很难把一次业务串起来）
