### ISSUE TITLE
怎么跟fastapi,sanic之类的框架整合？

### ISSUE THREAD

**Issue by ptcgh** [ydf0509/nb_log#71]
怎么跟fastapi,sanic之类的框架整合？我用的sanic框架，在下面的代码里面会在控制台同时打印出两条日志
from sanic import  Sanic
from sanic.log import logger
from nb_log import get_logger
get_logger("sanic")
app=Sanic("test")
在路由里面
logger.info("test")
在控制台会出现一条没彩色的日志(标准logging打印的)和一条彩色的日志(nb_log打印的)

**Comment by ydf0509** [comment]
fastapi和nblog结合的最佳实践，可以直接百度这个标题，然后csdn有一篇文章。

nblog和fastapi结合，比和flask djanho麻烦一点，因为ubicorn重新配置了日志loggongconfig字典，但是文章有nblog和fastapi的结合。还是要设置那个字典。

**Comment by ydf0509** [comment]
sanic没试过，但和fastapi结合有csdn博客

**Comment by ydf0509** [comment]
你可以看uvicorn config.py的代码，因为他里面重新设置了uvicorn 相关命名空间的日志handlers，所以提前getlogger被他重置了，所以uvicorn启动时候需要传递log_config.py字典。

**Comment by ptcgh** [comment]
参考那个csdn改了dict确实可以了，谢谢，你这个为啥没放一份gitee上？

**Comment by ptcgh** [comment]
谢谢大佬。
