### ISSUE TITLE
如何配置错误日志不要输出到普通文件中？

### ISSUE THREAD

**Issue by wang-xiaowu** [ydf0509/nb_log#72]
如何配置错误日志不要输出到普通文件中？
只能配置命名空间吗？

**Comment by ydf0509** [comment]
普通文件指的是什么文件? 你的需求写个demo代码出来,我看看

**Comment by wang-xiaowu** [comment]
```python
from nb_log import get_logger, LogManager

logger = get_logger('default',
                    do_not_use_color_handler=False,
                    log_file_size=100,
                    log_path='logs',
                    log_filename='nb_log.log',
                    is_add_stream_handler=True,
                    error_log_filename='error_nb_log.log')
```

![image](https://github.com/ydf0509/nb_log/assets/44340137/ebe8cac1-f87e-4614-a373-e8d1fefc193d)

![image](https://github.com/ydf0509/nb_log/assets/44340137/04920c2c-d3d5-499b-8d05-738096daadbd)

**Comment by ydf0509** [comment]
那就不能配置,为什么有这样的需求

**Comment by wang-xiaowu** [comment]
filebeat按文件分批采集日志到指定es索引,
如果一个文件里混着各种日志内容就不太好处理了

**Comment by ydf0509** [comment]
既然你用elk,为什么要把单独的错误日志写到错误文件呢? 为什么你要单独写到错误文件呢?elk不是可以按照 level级别检索吗

**Comment by ydf0509** [comment]
elk是和使用 json 格式日志,然后按照level字段检索.

**Comment by ydf0509** [comment]
如果你需要这样,可以继承handler,在handler里面重写级别过滤呢

**Comment by wang-xiaowu** [comment]
自定义loghandler吗, 我回头看下吧

**Comment by wang-xiaowu** [comment]
蟹蟹
