### ISSUE TITLE
控制台有两份打印

### ISSUE THREAD

**Issue by CoderHaay** [ydf0509/nb_log#76]
![image](https://github.com/user-attachments/assets/64dacb38-797d-4ccc-90b7-e70cda371f6c)
你好，系统打印的日志如何屏蔽掉呢？

**Comment by ydf0509** [comment]
写个能复现的精简demo来。看你怎么写的

**Comment by CoderHaay** [comment]
感谢回复。我原地建了个Demo就没问题，我再找找哪里不同。

**Comment by CoderHaay** [comment]
close
