### ISSUE TITLE
行数的最后一个数字也被染成彩色了

### ISSUE THREAD

**Issue by Jeasonlv** [ydf0509/nb_log#77]
![image](https://github.com/user-attachments/assets/c885317a-a0f6-4140-8584-68c17e406391)
提两个建议，一是行数的最后一个数字也被染成彩色了，二是文件的路径 “D:\work\testcode\Python_APITest\new\common\log_utils.py”   是不是以项目为根目录来展示比较方便看

**Comment by Jeasonlv** [comment]
还有就是文件路径   D:\work\testcode\Python_APITest\new\common\log_utils.py  是不是以项目为根目录展示比较好

**Comment by ydf0509** [comment]
1、最后一个数字有颜色，应该没印象吧，没找到解决办法。没强迫症就可以。

2、 全路径，是为了方便点击跳转到对应的文件。

**Comment by Jeasonlv** [comment]
> 1、最后一个行号的数字有颜色，应该没影响吧，没找到解决办法。没强迫症就可以。
> 
> 2、 全路径，是为了方便点击跳转到对应的文件，并且知道是哪个文件夹下的代码。

第二点可以接受，只不过是当路径比较深的时候展示出来会比较长，不管是放在日志信息前还是日志信息后都不太方便

**Comment by ydf0509** [comment]
目前可以通过日志模板设置，是需要全文件路径还是只要文件名，  但是没有提供相对路径。python logging的formatter没有支持相对路径的字段
