### ISSUE TITLE
日志无法输入到pythonlogs

### ISSUE THREAD

**Issue by yjyn01** [ydf0509/nb_log#8]
nb_log 在nohup uwsgi  xxx.ini >> nohup.log 的启动下，日志输入不到项目下的pythonlogs中， 如果是python manage.py的情况下市可以输入到pythonlog， 请问这个如何解决

**Comment by ydf0509** [comment]
看控制台，读取的是什么nb_log_config.py的位置，get_logger只要写了file_name入参一定会生成文件日志的，无非是生成到哪个文件夹的问题。linux现在默认是默认生成到/home/usernamexx/pythonlogs文件夹下，windows才是默认生成到/pythonlogs,因为linux文件权限严格，非root用户不能再磁盘根目录创建/pythonlogs文件夹

**Comment by ydf0509** [comment]
控制台已近说的很明确了，读取的是哪个文件的配置作为日志框架的配置
